/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMdslScopeProvider extends DelegatingScopeProvider {
}
