/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mdsl.parser.antlr.internal.InternalMdslParser;
import org.xtext.mdsl.services.MdslGrammarAccess;

public class MdslParser extends AbstractAntlrParser {

	@Inject
	private MdslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMdslParser createParser(XtextTokenStream stream) {
		return new InternalMdslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
