/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsl.mdsl.Action#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Action#getSuperAction <em>Super Action</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Action#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Action#getShellCmd <em>Shell Cmd</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Action#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsl.mdsl.MdslPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Action#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Super Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Action</em>' reference.
   * @see #setSuperAction(Action)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getAction_SuperAction()
   * @model
   * @generated
   */
  Action getSuperAction();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Action#getSuperAction <em>Super Action</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Action</em>' reference.
   * @see #getSuperAction()
   * @generated
   */
  void setSuperAction(Action value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getAction_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Action#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Shell Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shell Cmd</em>' attribute.
   * @see #setShellCmd(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getAction_ShellCmd()
   * @model
   * @generated
   */
  String getShellCmd();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Action#getShellCmd <em>Shell Cmd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shell Cmd</em>' attribute.
   * @see #getShellCmd()
   * @generated
   */
  void setShellCmd(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' attribute list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getAction_Params()
   * @model unique="false"
   * @generated
   */
  EList<String> getParams();

} // Action
