/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mdsl.mdsl.MdslFactory
 * @model kind="package"
 * @generated
 */
public interface MdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mdsl/Mdsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MdslPackage eINSTANCE = org.xtext.mdsl.mdsl.impl.MdslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.ModelImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.DeclarationImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.SystemImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Modes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__MODES = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operating System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__OPERATING_SYSTEM = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Distribution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__DISTRIBUTION = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Release</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__RELEASE = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.SoftwareImpl <em>Software</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.SoftwareImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSoftware()
   * @generated
   */
  int SOFTWARE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOFTWARE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vendor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOFTWARE__VENDOR = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Product</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOFTWARE__PRODUCT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOFTWARE__VERSION = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOFTWARE__PACKAGE = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Software</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOFTWARE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.ModeImpl <em>Mode</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.ModeImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getMode()
   * @generated
   */
  int MODE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Super Mode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__SUPER_MODE = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__DESCRIPTION = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__PRIORITY = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Start Services</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__START_SERVICES = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Stop Services</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__STOP_SERVICES = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Enabled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__ENABLED = DECLARATION_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Alternative Modes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE__ALTERNATIVE_MODES = DECLARATION_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Mode</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.ServiceImpl <em>Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.ServiceImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getService()
   * @generated
   */
  int SERVICE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Uses Software</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__USES_SOFTWARE = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Start Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__START_ACTIONS = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Stop Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__STOP_ACTIONS = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.ActionWithParamsImpl <em>Action With Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.ActionWithParamsImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getActionWithParams()
   * @generated
   */
  int ACTION_WITH_PARAMS = 6;

  /**
   * The feature id for the '<em><b>Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_WITH_PARAMS__ACTION = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_WITH_PARAMS__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Action With Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_WITH_PARAMS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.ActionImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Super Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__SUPER_ACTION = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DESCRIPTION = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Shell Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__SHELL_CMD = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PARAMS = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.RuleImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getRule()
   * @generated
   */
  int RULE = 8;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__DESCRIPTION = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>If</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__IF = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Current Mode</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CURRENT_MODE = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Modes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__MODES = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Then</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__THEN = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Else</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ELSE = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.impl.EventImpl
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DESCRIPTION = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS <em>SUPPORTED OPERATING SYSTEMS</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSUPPORTED_OPERATING_SYSTEMS()
   * @generated
   */
  int SUPPORTED_OPERATING_SYSTEMS = 10;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS <em>SUPPORTED DISTRIBUTIONS</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSUPPORTED_DISTRIBUTIONS()
   * @generated
   */
  int SUPPORTED_DISTRIBUTIONS = 11;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.SUPPORTED_RELEASES <em>SUPPORTED RELEASES</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.SUPPORTED_RELEASES
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSUPPORTED_RELEASES()
   * @generated
   */
  int SUPPORTED_RELEASES = 12;

  /**
   * The meta object id for the '{@link org.xtext.mdsl.mdsl.Enabled <em>Enabled</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdsl.mdsl.Enabled
   * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getEnabled()
   * @generated
   */
  int ENABLED = 13;


  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.mdsl.mdsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mdsl.mdsl.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.xtext.mdsl.mdsl.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.mdsl.mdsl.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.mdsl.mdsl.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.System#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdsl.mdsl.System#getName()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.System#getModes <em>Modes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Modes</em>'.
   * @see org.xtext.mdsl.mdsl.System#getModes()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Modes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.System#getOperatingSystem <em>Operating System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operating System</em>'.
   * @see org.xtext.mdsl.mdsl.System#getOperatingSystem()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_OperatingSystem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.System#getDistribution <em>Distribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distribution</em>'.
   * @see org.xtext.mdsl.mdsl.System#getDistribution()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Distribution();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.System#getRelease <em>Release</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Release</em>'.
   * @see org.xtext.mdsl.mdsl.System#getRelease()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Release();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Software <em>Software</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Software</em>'.
   * @see org.xtext.mdsl.mdsl.Software
   * @generated
   */
  EClass getSoftware();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Software#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdsl.mdsl.Software#getName()
   * @see #getSoftware()
   * @generated
   */
  EAttribute getSoftware_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Software#getVendor <em>Vendor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vendor</em>'.
   * @see org.xtext.mdsl.mdsl.Software#getVendor()
   * @see #getSoftware()
   * @generated
   */
  EAttribute getSoftware_Vendor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Software#getProduct <em>Product</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Product</em>'.
   * @see org.xtext.mdsl.mdsl.Software#getProduct()
   * @see #getSoftware()
   * @generated
   */
  EAttribute getSoftware_Product();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Software#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.mdsl.mdsl.Software#getVersion()
   * @see #getSoftware()
   * @generated
   */
  EAttribute getSoftware_Version();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Software#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package</em>'.
   * @see org.xtext.mdsl.mdsl.Software#getPackage()
   * @see #getSoftware()
   * @generated
   */
  EAttribute getSoftware_Package();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Mode <em>Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mode</em>'.
   * @see org.xtext.mdsl.mdsl.Mode
   * @generated
   */
  EClass getMode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Mode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getName()
   * @see #getMode()
   * @generated
   */
  EAttribute getMode_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.mdsl.mdsl.Mode#getSuperMode <em>Super Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Mode</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getSuperMode()
   * @see #getMode()
   * @generated
   */
  EReference getMode_SuperMode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Mode#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getDescription()
   * @see #getMode()
   * @generated
   */
  EAttribute getMode_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Mode#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getPriority()
   * @see #getMode()
   * @generated
   */
  EAttribute getMode_Priority();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Mode#getStartServices <em>Start Services</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Start Services</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getStartServices()
   * @see #getMode()
   * @generated
   */
  EReference getMode_StartServices();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Mode#getStopServices <em>Stop Services</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Stop Services</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getStopServices()
   * @see #getMode()
   * @generated
   */
  EReference getMode_StopServices();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Mode#getEnabled <em>Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Enabled</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getEnabled()
   * @see #getMode()
   * @generated
   */
  EAttribute getMode_Enabled();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Mode#getAlternativeModes <em>Alternative Modes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Alternative Modes</em>'.
   * @see org.xtext.mdsl.mdsl.Mode#getAlternativeModes()
   * @see #getMode()
   * @generated
   */
  EReference getMode_AlternativeModes();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service</em>'.
   * @see org.xtext.mdsl.mdsl.Service
   * @generated
   */
  EClass getService();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Service#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdsl.mdsl.Service#getName()
   * @see #getService()
   * @generated
   */
  EAttribute getService_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Service#getUsesSoftware <em>Uses Software</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Uses Software</em>'.
   * @see org.xtext.mdsl.mdsl.Service#getUsesSoftware()
   * @see #getService()
   * @generated
   */
  EReference getService_UsesSoftware();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mdsl.mdsl.Service#getStartActions <em>Start Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Start Actions</em>'.
   * @see org.xtext.mdsl.mdsl.Service#getStartActions()
   * @see #getService()
   * @generated
   */
  EReference getService_StartActions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mdsl.mdsl.Service#getStopActions <em>Stop Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stop Actions</em>'.
   * @see org.xtext.mdsl.mdsl.Service#getStopActions()
   * @see #getService()
   * @generated
   */
  EReference getService_StopActions();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.ActionWithParams <em>Action With Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action With Params</em>'.
   * @see org.xtext.mdsl.mdsl.ActionWithParams
   * @generated
   */
  EClass getActionWithParams();

  /**
   * Returns the meta object for the reference '{@link org.xtext.mdsl.mdsl.ActionWithParams#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Action</em>'.
   * @see org.xtext.mdsl.mdsl.ActionWithParams#getAction()
   * @see #getActionWithParams()
   * @generated
   */
  EReference getActionWithParams_Action();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.mdsl.mdsl.ActionWithParams#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see org.xtext.mdsl.mdsl.ActionWithParams#getParams()
   * @see #getActionWithParams()
   * @generated
   */
  EAttribute getActionWithParams_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.mdsl.mdsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdsl.mdsl.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.mdsl.mdsl.Action#getSuperAction <em>Super Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Action</em>'.
   * @see org.xtext.mdsl.mdsl.Action#getSuperAction()
   * @see #getAction()
   * @generated
   */
  EReference getAction_SuperAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Action#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.mdsl.mdsl.Action#getDescription()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Action#getShellCmd <em>Shell Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Shell Cmd</em>'.
   * @see org.xtext.mdsl.mdsl.Action#getShellCmd()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_ShellCmd();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.mdsl.mdsl.Action#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see org.xtext.mdsl.mdsl.Action#getParams()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.mdsl.mdsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Rule#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.mdsl.mdsl.Rule#getDescription()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Description();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Rule#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>If</em>'.
   * @see org.xtext.mdsl.mdsl.Rule#getIf()
   * @see #getRule()
   * @generated
   */
  EReference getRule_If();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Rule#getCurrentMode <em>Current Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Current Mode</em>'.
   * @see org.xtext.mdsl.mdsl.Rule#getCurrentMode()
   * @see #getRule()
   * @generated
   */
  EReference getRule_CurrentMode();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.mdsl.mdsl.Rule#getModes <em>Modes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Modes</em>'.
   * @see org.xtext.mdsl.mdsl.Rule#getModes()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Modes();

  /**
   * Returns the meta object for the reference '{@link org.xtext.mdsl.mdsl.Rule#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Then</em>'.
   * @see org.xtext.mdsl.mdsl.Rule#getThen()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Then();

  /**
   * Returns the meta object for the reference '{@link org.xtext.mdsl.mdsl.Rule#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Else</em>'.
   * @see org.xtext.mdsl.mdsl.Rule#getElse()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Else();

  /**
   * Returns the meta object for class '{@link org.xtext.mdsl.mdsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.xtext.mdsl.mdsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdsl.mdsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdsl.mdsl.Event#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.mdsl.mdsl.Event#getDescription()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Description();

  /**
   * Returns the meta object for enum '{@link org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS <em>SUPPORTED OPERATING SYSTEMS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SUPPORTED OPERATING SYSTEMS</em>'.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS
   * @generated
   */
  EEnum getSUPPORTED_OPERATING_SYSTEMS();

  /**
   * Returns the meta object for enum '{@link org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS <em>SUPPORTED DISTRIBUTIONS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SUPPORTED DISTRIBUTIONS</em>'.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS
   * @generated
   */
  EEnum getSUPPORTED_DISTRIBUTIONS();

  /**
   * Returns the meta object for enum '{@link org.xtext.mdsl.mdsl.SUPPORTED_RELEASES <em>SUPPORTED RELEASES</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SUPPORTED RELEASES</em>'.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_RELEASES
   * @generated
   */
  EEnum getSUPPORTED_RELEASES();

  /**
   * Returns the meta object for enum '{@link org.xtext.mdsl.mdsl.Enabled <em>Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Enabled</em>'.
   * @see org.xtext.mdsl.mdsl.Enabled
   * @generated
   */
  EEnum getEnabled();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MdslFactory getMdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.ModelImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATIONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.DeclarationImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.SystemImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__NAME = eINSTANCE.getSystem_Name();

    /**
     * The meta object literal for the '<em><b>Modes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__MODES = eINSTANCE.getSystem_Modes();

    /**
     * The meta object literal for the '<em><b>Operating System</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__OPERATING_SYSTEM = eINSTANCE.getSystem_OperatingSystem();

    /**
     * The meta object literal for the '<em><b>Distribution</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__DISTRIBUTION = eINSTANCE.getSystem_Distribution();

    /**
     * The meta object literal for the '<em><b>Release</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__RELEASE = eINSTANCE.getSystem_Release();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.SoftwareImpl <em>Software</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.SoftwareImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSoftware()
     * @generated
     */
    EClass SOFTWARE = eINSTANCE.getSoftware();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOFTWARE__NAME = eINSTANCE.getSoftware_Name();

    /**
     * The meta object literal for the '<em><b>Vendor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOFTWARE__VENDOR = eINSTANCE.getSoftware_Vendor();

    /**
     * The meta object literal for the '<em><b>Product</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOFTWARE__PRODUCT = eINSTANCE.getSoftware_Product();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOFTWARE__VERSION = eINSTANCE.getSoftware_Version();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOFTWARE__PACKAGE = eINSTANCE.getSoftware_Package();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.ModeImpl <em>Mode</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.ModeImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getMode()
     * @generated
     */
    EClass MODE = eINSTANCE.getMode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODE__NAME = eINSTANCE.getMode_Name();

    /**
     * The meta object literal for the '<em><b>Super Mode</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODE__SUPER_MODE = eINSTANCE.getMode_SuperMode();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODE__DESCRIPTION = eINSTANCE.getMode_Description();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODE__PRIORITY = eINSTANCE.getMode_Priority();

    /**
     * The meta object literal for the '<em><b>Start Services</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODE__START_SERVICES = eINSTANCE.getMode_StartServices();

    /**
     * The meta object literal for the '<em><b>Stop Services</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODE__STOP_SERVICES = eINSTANCE.getMode_StopServices();

    /**
     * The meta object literal for the '<em><b>Enabled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODE__ENABLED = eINSTANCE.getMode_Enabled();

    /**
     * The meta object literal for the '<em><b>Alternative Modes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODE__ALTERNATIVE_MODES = eINSTANCE.getMode_AlternativeModes();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.ServiceImpl <em>Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.ServiceImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getService()
     * @generated
     */
    EClass SERVICE = eINSTANCE.getService();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE__NAME = eINSTANCE.getService_Name();

    /**
     * The meta object literal for the '<em><b>Uses Software</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__USES_SOFTWARE = eINSTANCE.getService_UsesSoftware();

    /**
     * The meta object literal for the '<em><b>Start Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__START_ACTIONS = eINSTANCE.getService_StartActions();

    /**
     * The meta object literal for the '<em><b>Stop Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__STOP_ACTIONS = eINSTANCE.getService_StopActions();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.ActionWithParamsImpl <em>Action With Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.ActionWithParamsImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getActionWithParams()
     * @generated
     */
    EClass ACTION_WITH_PARAMS = eINSTANCE.getActionWithParams();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_WITH_PARAMS__ACTION = eINSTANCE.getActionWithParams_Action();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION_WITH_PARAMS__PARAMS = eINSTANCE.getActionWithParams_Params();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.ActionImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '<em><b>Super Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__SUPER_ACTION = eINSTANCE.getAction_SuperAction();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DESCRIPTION = eINSTANCE.getAction_Description();

    /**
     * The meta object literal for the '<em><b>Shell Cmd</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__SHELL_CMD = eINSTANCE.getAction_ShellCmd();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__PARAMS = eINSTANCE.getAction_Params();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.RuleImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__DESCRIPTION = eINSTANCE.getRule_Description();

    /**
     * The meta object literal for the '<em><b>If</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__IF = eINSTANCE.getRule_If();

    /**
     * The meta object literal for the '<em><b>Current Mode</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CURRENT_MODE = eINSTANCE.getRule_CurrentMode();

    /**
     * The meta object literal for the '<em><b>Modes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__MODES = eINSTANCE.getRule_Modes();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__THEN = eINSTANCE.getRule_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ELSE = eINSTANCE.getRule_Else();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.impl.EventImpl
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__DESCRIPTION = eINSTANCE.getEvent_Description();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS <em>SUPPORTED OPERATING SYSTEMS</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSUPPORTED_OPERATING_SYSTEMS()
     * @generated
     */
    EEnum SUPPORTED_OPERATING_SYSTEMS = eINSTANCE.getSUPPORTED_OPERATING_SYSTEMS();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS <em>SUPPORTED DISTRIBUTIONS</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSUPPORTED_DISTRIBUTIONS()
     * @generated
     */
    EEnum SUPPORTED_DISTRIBUTIONS = eINSTANCE.getSUPPORTED_DISTRIBUTIONS();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.SUPPORTED_RELEASES <em>SUPPORTED RELEASES</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.SUPPORTED_RELEASES
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getSUPPORTED_RELEASES()
     * @generated
     */
    EEnum SUPPORTED_RELEASES = eINSTANCE.getSUPPORTED_RELEASES();

    /**
     * The meta object literal for the '{@link org.xtext.mdsl.mdsl.Enabled <em>Enabled</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdsl.mdsl.Enabled
     * @see org.xtext.mdsl.mdsl.impl.MdslPackageImpl#getEnabled()
     * @generated
     */
    EEnum ENABLED = eINSTANCE.getEnabled();

  }

} //MdslPackage
