/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mode</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getSuperMode <em>Super Mode</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getPriority <em>Priority</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getStartServices <em>Start Services</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getStopServices <em>Stop Services</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getEnabled <em>Enabled</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Mode#getAlternativeMode <em>Alternative Mode</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsl.mdsl.MdslPackage#getMode()
 * @model
 * @generated
 */
public interface Mode extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Mode#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Super Mode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Mode</em>' reference.
   * @see #setSuperMode(Mode)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_SuperMode()
   * @model
   * @generated
   */
  Mode getSuperMode();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Mode#getSuperMode <em>Super Mode</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Mode</em>' reference.
   * @see #getSuperMode()
   * @generated
   */
  void setSuperMode(Mode value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Mode#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see #setPriority(int)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_Priority()
   * @model
   * @generated
   */
  int getPriority();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Mode#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see #getPriority()
   * @generated
   */
  void setPriority(int value);

  /**
   * Returns the value of the '<em><b>Start Services</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.Service}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Services</em>' reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_StartServices()
   * @model
   * @generated
   */
  EList<Service> getStartServices();

  /**
   * Returns the value of the '<em><b>Stop Services</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.Service}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop Services</em>' reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_StopServices()
   * @model
   * @generated
   */
  EList<Service> getStopServices();

  /**
   * Returns the value of the '<em><b>Enabled</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mdsl.mdsl.Enabled}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enabled</em>' attribute.
   * @see org.xtext.mdsl.mdsl.Enabled
   * @see #setEnabled(Enabled)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_Enabled()
   * @model
   * @generated
   */
  Enabled getEnabled();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Mode#getEnabled <em>Enabled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enabled</em>' attribute.
   * @see org.xtext.mdsl.mdsl.Enabled
   * @see #getEnabled()
   * @generated
   */
  void setEnabled(Enabled value);

  /**
   * Returns the value of the '<em><b>Alternative Mode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alternative Mode</em>' reference.
   * @see #setAlternativeMode(Mode)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getMode_AlternativeMode()
   * @model
   * @generated
   */
  Mode getAlternativeMode();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Mode#getAlternativeMode <em>Alternative Mode</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alternative Mode</em>' reference.
   * @see #getAlternativeMode()
   * @generated
   */
  void setAlternativeMode(Mode value);

} // Mode
