/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsl.mdsl.Service#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Service#getUsesSoftware <em>Uses Software</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Service#getStartActions <em>Start Actions</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Service#getStopActions <em>Stop Actions</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsl.mdsl.MdslPackage#getService()
 * @model
 * @generated
 */
public interface Service extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getService_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Service#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Uses Software</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.Software}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uses Software</em>' reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getService_UsesSoftware()
   * @model
   * @generated
   */
  EList<Software> getUsesSoftware();

  /**
   * Returns the value of the '<em><b>Start Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.ActionWithParams}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Actions</em>' containment reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getService_StartActions()
   * @model containment="true"
   * @generated
   */
  EList<ActionWithParams> getStartActions();

  /**
   * Returns the value of the '<em><b>Stop Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.ActionWithParams}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop Actions</em>' containment reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getService_StopActions()
   * @model containment="true"
   * @generated
   */
  EList<ActionWithParams> getStopActions();

} // Service
