/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Software</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsl.mdsl.Software#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Software#getVendor <em>Vendor</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Software#getProduct <em>Product</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Software#getVersion <em>Version</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.Software#getPackage <em>Package</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsl.mdsl.MdslPackage#getSoftware()
 * @model
 * @generated
 */
public interface Software extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSoftware_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Software#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Vendor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vendor</em>' attribute.
   * @see #setVendor(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSoftware_Vendor()
   * @model
   * @generated
   */
  String getVendor();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Software#getVendor <em>Vendor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vendor</em>' attribute.
   * @see #getVendor()
   * @generated
   */
  void setVendor(String value);

  /**
   * Returns the value of the '<em><b>Product</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product</em>' attribute.
   * @see #setProduct(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSoftware_Product()
   * @model
   * @generated
   */
  String getProduct();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Software#getProduct <em>Product</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Product</em>' attribute.
   * @see #getProduct()
   * @generated
   */
  void setProduct(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSoftware_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Software#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' attribute.
   * @see #setPackage(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSoftware_Package()
   * @model
   * @generated
   */
  String getPackage();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.Software#getPackage <em>Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' attribute.
   * @see #getPackage()
   * @generated
   */
  void setPackage(String value);

} // Software
