/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>SUPPORTED DISTRIBUTIONS</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.mdsl.mdsl.MdslPackage#getSUPPORTED_DISTRIBUTIONS()
 * @model
 * @generated
 */
public enum SUPPORTED_DISTRIBUTIONS implements Enumerator
{
  /**
   * The '<em><b>Debian</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEBIAN_VALUE
   * @generated
   * @ordered
   */
  DEBIAN(0, "Debian", "Debian"),

  /**
   * The '<em><b>Ubuntu</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UBUNTU_VALUE
   * @generated
   * @ordered
   */
  UBUNTU(1, "Ubuntu", "Ubuntu"),

  /**
   * The '<em><b>Other</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OTHER_VALUE
   * @generated
   * @ordered
   */
  OTHER(2, "Other", "Other");

  /**
   * The '<em><b>Debian</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEBIAN
   * @model name="Debian"
   * @generated
   * @ordered
   */
  public static final int DEBIAN_VALUE = 0;

  /**
   * The '<em><b>Ubuntu</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UBUNTU
   * @model name="Ubuntu"
   * @generated
   * @ordered
   */
  public static final int UBUNTU_VALUE = 1;

  /**
   * The '<em><b>Other</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OTHER
   * @model name="Other"
   * @generated
   * @ordered
   */
  public static final int OTHER_VALUE = 2;

  /**
   * An array of all the '<em><b>SUPPORTED DISTRIBUTIONS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SUPPORTED_DISTRIBUTIONS[] VALUES_ARRAY =
    new SUPPORTED_DISTRIBUTIONS[]
    {
      DEBIAN,
      UBUNTU,
      OTHER,
    };

  /**
   * A public read-only list of all the '<em><b>SUPPORTED DISTRIBUTIONS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SUPPORTED_DISTRIBUTIONS> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>SUPPORTED DISTRIBUTIONS</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUPPORTED_DISTRIBUTIONS get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SUPPORTED_DISTRIBUTIONS result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SUPPORTED DISTRIBUTIONS</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUPPORTED_DISTRIBUTIONS getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SUPPORTED_DISTRIBUTIONS result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SUPPORTED DISTRIBUTIONS</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUPPORTED_DISTRIBUTIONS get(int value)
  {
    switch (value)
    {
      case DEBIAN_VALUE: return DEBIAN;
      case UBUNTU_VALUE: return UBUNTU;
      case OTHER_VALUE: return OTHER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SUPPORTED_DISTRIBUTIONS(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SUPPORTED_DISTRIBUTIONS
