/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>SUPPORTED OPERATING SYSTEMS</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.mdsl.mdsl.MdslPackage#getSUPPORTED_OPERATING_SYSTEMS()
 * @model
 * @generated
 */
public enum SUPPORTED_OPERATING_SYSTEMS implements Enumerator
{
  /**
   * The '<em><b>Windows</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WINDOWS_VALUE
   * @generated
   * @ordered
   */
  WINDOWS(0, "Windows", "Windows"),

  /**
   * The '<em><b>Linux</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINUX_VALUE
   * @generated
   * @ordered
   */
  LINUX(1, "Linux", "Linux");

  /**
   * The '<em><b>Windows</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WINDOWS
   * @model name="Windows"
   * @generated
   * @ordered
   */
  public static final int WINDOWS_VALUE = 0;

  /**
   * The '<em><b>Linux</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINUX
   * @model name="Linux"
   * @generated
   * @ordered
   */
  public static final int LINUX_VALUE = 1;

  /**
   * An array of all the '<em><b>SUPPORTED OPERATING SYSTEMS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SUPPORTED_OPERATING_SYSTEMS[] VALUES_ARRAY =
    new SUPPORTED_OPERATING_SYSTEMS[]
    {
      WINDOWS,
      LINUX,
    };

  /**
   * A public read-only list of all the '<em><b>SUPPORTED OPERATING SYSTEMS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SUPPORTED_OPERATING_SYSTEMS> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>SUPPORTED OPERATING SYSTEMS</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUPPORTED_OPERATING_SYSTEMS get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SUPPORTED_OPERATING_SYSTEMS result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SUPPORTED OPERATING SYSTEMS</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUPPORTED_OPERATING_SYSTEMS getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SUPPORTED_OPERATING_SYSTEMS result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SUPPORTED OPERATING SYSTEMS</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUPPORTED_OPERATING_SYSTEMS get(int value)
  {
    switch (value)
    {
      case WINDOWS_VALUE: return WINDOWS;
      case LINUX_VALUE: return LINUX;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SUPPORTED_OPERATING_SYSTEMS(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SUPPORTED_OPERATING_SYSTEMS
