/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getModes <em>Modes</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getDistribution <em>Distribution</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getReleaseDate <em>Release Date</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Modes</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.Mode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modes</em>' reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Modes()
   * @model
   * @generated
   */
  EList<Mode> getModes();

  /**
   * Returns the value of the '<em><b>Distribution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distribution</em>' attribute.
   * @see #setDistribution(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Distribution()
   * @model
   * @generated
   */
  String getDistribution();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getDistribution <em>Distribution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distribution</em>' attribute.
   * @see #getDistribution()
   * @generated
   */
  void setDistribution(String value);

  /**
   * Returns the value of the '<em><b>Release Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Release Date</em>' attribute.
   * @see #setReleaseDate(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_ReleaseDate()
   * @model
   * @generated
   */
  String getReleaseDate();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getReleaseDate <em>Release Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Release Date</em>' attribute.
   * @see #getReleaseDate()
   * @generated
   */
  void setReleaseDate(String value);

} // System
