/**
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl.mdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getModes <em>Modes</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getOperatingSystem <em>Operating System</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getDistribution <em>Distribution</em>}</li>
 *   <li>{@link org.xtext.mdsl.mdsl.System#getRelease <em>Release</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Modes</b></em>' reference list.
   * The list contents are of type {@link org.xtext.mdsl.mdsl.Mode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modes</em>' reference list.
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Modes()
   * @model
   * @generated
   */
  EList<Mode> getModes();

  /**
   * Returns the value of the '<em><b>Operating System</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operating System</em>' attribute.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS
   * @see #setOperatingSystem(SUPPORTED_OPERATING_SYSTEMS)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_OperatingSystem()
   * @model
   * @generated
   */
  SUPPORTED_OPERATING_SYSTEMS getOperatingSystem();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getOperatingSystem <em>Operating System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operating System</em>' attribute.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_OPERATING_SYSTEMS
   * @see #getOperatingSystem()
   * @generated
   */
  void setOperatingSystem(SUPPORTED_OPERATING_SYSTEMS value);

  /**
   * Returns the value of the '<em><b>Distribution</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distribution</em>' attribute.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS
   * @see #setDistribution(SUPPORTED_DISTRIBUTIONS)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Distribution()
   * @model
   * @generated
   */
  SUPPORTED_DISTRIBUTIONS getDistribution();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getDistribution <em>Distribution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distribution</em>' attribute.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_DISTRIBUTIONS
   * @see #getDistribution()
   * @generated
   */
  void setDistribution(SUPPORTED_DISTRIBUTIONS value);

  /**
   * Returns the value of the '<em><b>Release</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mdsl.mdsl.SUPPORTED_RELEASES}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Release</em>' attribute.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_RELEASES
   * @see #setRelease(SUPPORTED_RELEASES)
   * @see org.xtext.mdsl.mdsl.MdslPackage#getSystem_Release()
   * @model
   * @generated
   */
  SUPPORTED_RELEASES getRelease();

  /**
   * Sets the value of the '{@link org.xtext.mdsl.mdsl.System#getRelease <em>Release</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Release</em>' attribute.
   * @see org.xtext.mdsl.mdsl.SUPPORTED_RELEASES
   * @see #getRelease()
   * @generated
   */
  void setRelease(SUPPORTED_RELEASES value);

} // System
