/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MdslStandaloneSetup extends MdslStandaloneSetupGenerated {

	public static void doSetup() {
		new MdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
